### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by mkupiniak** [jnbarlow/passport-hubspot-auth#1]
In the "Install" section of README, currently it says:
`$ npm install passport-hubspot-oauth2` - but this is different package than yours that, on the side, is not working properly

please change to:
`$ npm install passport-hubspot-auth` - your package ;)

**Comment by jnbarlow** [comment]
Doh... Thank you for that.  :)  

yeah, that package is the one I based mine on specifically because it wasn't working properly.
